/**
 * Prospect Source Service
 *
 * Data-access layer for the Formulários feature.
 * Covers: prospect_sources, prospect_columns, prospect_leads.
 *
 * Conventions followed:
 *  - Import supabase from "@/integrations/supabase/client"
 *  - Cast untyped tables with `as any` (tables not yet in generated types)
 *  - Re-throw Supabase errors directly (callers handle UI feedback)
 *  - No UI logic, no toasts — this is a pure data layer
 */

import { supabase } from "@/integrations/supabase/client";
import type { ProspectSource, ProspectColumn, ProspectLead } from "@/types/prospect";

// ─── Sources ──────────────────────────────────────────────────────────────────

/**
 * List all webhook sources for an organisation, newest first.
 */
export async function getSources(organizationId: string): Promise<ProspectSource[]> {
  const { data, error } = await supabase
    .from("prospect_sources" as any)
    .select("*")
    .eq("organization_id", organizationId)
    .order("created_at", { ascending: false });

  if (error) throw error;
  return (data ?? []) as unknown as ProspectSource[];
}

/**
 * Create a new webhook source for an organisation.
 * The webhook_token is generated by the DB default.
 */
export async function createSource(
  organizationId: string,
  name: string,
): Promise<ProspectSource> {
  const { data, error } = await supabase
    .from("prospect_sources" as any)
    .insert({ organization_id: organizationId, name })
    .select("*")
    .single();

  if (error) throw error;
  return data as unknown as ProspectSource;
}

/**
 * Update mutable fields of a source (name and/or is_active).
 */
export async function updateSource(
  id: string,
  updates: Partial<Pick<ProspectSource, "name" | "is_active">>,
): Promise<ProspectSource> {
  const { data, error } = await supabase
    .from("prospect_sources" as any)
    .update({ ...updates, updated_at: new Date().toISOString() })
    .eq("id", id)
    .select("*")
    .single();

  if (error) throw error;
  return data as unknown as ProspectSource;
}

/**
 * Permanently delete a source and all its columns and leads (ON DELETE CASCADE).
 */
export async function deleteSource(id: string): Promise<void> {
  const { error } = await supabase
    .from("prospect_sources" as any)
    .delete()
    .eq("id", id);

  if (error) throw error;
}

// ─── Columns ─────────────────────────────────────────────────────────────────

/**
 * List configured columns for a source, in display order.
 */
export async function getColumns(sourceId: string): Promise<ProspectColumn[]> {
  const { data, error } = await supabase
    .from("prospect_columns" as any)
    .select("*")
    .eq("source_id", sourceId)
    .order("col_order", { ascending: true });

  if (error) throw error;
  return (data ?? []) as unknown as ProspectColumn[];
}

/**
 * Create or update a column.
 * Provide `id` to update an existing row; omit it to insert a new one.
 * Uses ON CONFLICT (source_id, key_name) via upsert for idempotency.
 */
export async function upsertColumn(
  column: Omit<ProspectColumn, "id" | "created_at"> & { id?: string },
): Promise<ProspectColumn> {
  const payload: Record<string, unknown> = {
    source_id: column.source_id,
    key_name: column.key_name,
    label: column.label,
    col_type: column.col_type,
    select_options: column.select_options,
    col_order: column.col_order,
  };

  if (column.id) {
    // Update existing row by PK
    const { data, error } = await supabase
      .from("prospect_columns" as any)
      .update(payload)
      .eq("id", column.id)
      .select("*")
      .single();

    if (error) throw error;
    return data as unknown as ProspectColumn;
  }

  // Insert new row; DB UNIQUE(source_id, key_name) guards duplicates
  const { data, error } = await supabase
    .from("prospect_columns" as any)
    .insert(payload)
    .select("*")
    .single();

  if (error) throw error;
  return data as unknown as ProspectColumn;
}

/**
 * Delete a column by id.
 */
export async function deleteColumn(id: string): Promise<void> {
  const { error } = await supabase
    .from("prospect_columns" as any)
    .delete()
    .eq("id", id);

  if (error) throw error;
}

/**
 * Batch-update col_order for multiple columns.
 * Executed as sequential updates (Supabase JS v2 has no bulk-update in one call).
 * If any update fails the error is thrown immediately.
 *
 * NOTE: @dnd-kit is NOT installed in this project (checked package.json).
 * Drag-and-drop reordering should be implemented with a different library
 * or a simple up/down button approach. This function is the data layer
 * and works regardless of the UI mechanism used.
 */
export async function reorderColumns(
  updates: { id: string; col_order: number }[],
): Promise<void> {
  for (const { id, col_order } of updates) {
    const { error } = await supabase
      .from("prospect_columns" as any)
      .update({ col_order })
      .eq("id", id);

    if (error) throw error;
  }
}

// ─── Leads ───────────────────────────────────────────────────────────────────

/**
 * Fetch a paginated page of leads for a source, newest first.
 * Returns both the rows and the total count for pagination UI.
 */
export async function getLeads(
  sourceId: string,
  page: number,
  pageSize: number,
): Promise<{ data: ProspectLead[]; count: number }> {
  const from = page * pageSize;
  const to = from + pageSize - 1;

  const { data, error, count } = await supabase
    .from("prospect_leads" as any)
    .select("*", { count: "exact" })
    .eq("source_id", sourceId)
    .order("received_at", { ascending: false })
    .range(from, to);

  if (error) throw error;
  return {
    data: (data ?? []) as unknown as ProspectLead[],
    count: count ?? 0,
  };
}

/**
 * Overwrite the field_data map for a lead (inline cell editing).
 * updated_at is set to now() on the DB side via the trigger, but we
 * also send it explicitly so optimistic UI can reflect it immediately.
 */
export async function updateLeadFieldData(
  leadId: string,
  fieldData: Record<string, string>,
): Promise<void> {
  const { error } = await supabase
    .from("prospect_leads" as any)
    .update({
      field_data: fieldData,
      updated_at: new Date().toISOString(),
    })
    .eq("id", leadId);

  if (error) throw error;
}

/**
 * Permanently delete multiple leads by id.
 */
export async function deleteLeads(ids: string[]): Promise<void> {
  const { error } = await supabase
    .from("prospect_leads" as any)
    .delete()
    .in("id", ids);

  if (error) throw error;
}

// ─── CSV Export ──────────────────────────────────────────────────────────────

/**
 * Fetch ALL leads for a source and return a UTF-8 CSV string.
 *
 * Column layout:
 *   "Recebido em" (DD/MM/YYYY HH:mm), then one column per ProspectColumn
 *   in col_order, using the column's `label` as the header.
 *
 * Values come from lead.field_data[column.key_name].
 * Missing values are rendered as an empty string.
 * Values are quoted and internal double-quotes are escaped.
 */
export async function exportLeadsAsCSV(
  sourceId: string,
  columns: ProspectColumn[],
  selectedLeadIds?: string[],
): Promise<string> {
  let query = supabase
    .from("prospect_leads" as any)
    .select("*")
    .eq("source_id", sourceId)
    .order("received_at", { ascending: false });

  if (selectedLeadIds && selectedLeadIds.length > 0) {
    query = query.in("id", selectedLeadIds);
  }

  const { data, error } = await query;

  if (error) throw error;

  const leads = (data ?? []) as unknown as ProspectLead[];

  // Sort columns by col_order ascending (defensive — caller may pass unsorted)
  const sortedColumns = [...columns].sort((a, b) => a.col_order - b.col_order);

  // CSV escape: wrap in double-quotes, escape inner double-quotes as ""
  const csvCell = (value: string): string =>
    `"${value.replace(/"/g, '""')}"`;

  // Header row
  const headers = ["Recebido em", ...sortedColumns.map((c) => c.label)];
  const headerRow = headers.map(csvCell).join(",");

  // Data rows
  const dataRows = leads.map((lead) => {
    const receivedAt = formatDateBR(lead.received_at);
    const cells = [
      receivedAt,
      ...sortedColumns.map((col) => lead.field_data[col.key_name] ?? ""),
    ];
    return cells.map(csvCell).join(",");
  });

  return [headerRow, ...dataRows].join("\r\n");
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Format an ISO 8601 timestamp as "DD/MM/YYYY HH:mm" in local time.
 */
function formatDateBR(iso: string): string {
  const d = new Date(iso);
  if (isNaN(d.getTime())) return iso; // fallback: return raw string

  const pad = (n: number) => String(n).padStart(2, "0");
  return (
    `${pad(d.getDate())}/${pad(d.getMonth() + 1)}/${d.getFullYear()} ` +
    `${pad(d.getHours())}:${pad(d.getMinutes())}`
  );
}
